### PR TITLE
1.11.0 Master mergen Kappa

### PR DESCRIPTION
**Pull request by Last0xygen**
Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa Kappa

### CODE REVIEW

**Comment by pongo1231** [comment]
I don't approve

**Review by Regynate — APPROVED** [review]

**Review by dawid2202 — APPROVED** [review]
game2Stable

**Comment by Mo-xii** [comment]
Okay, so now I know who to blame for the instability that this new branch is going to create

**Comment by Last0xygen** [comment]
> Okay, so now I know who to blame for the instability that this new branch is going to create

Yeah, damn dawid and reguas 😏

**Pull request merged**
